name: run

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'
        cache-dependency-path: requirements.txt
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Cache Camoufox
      uses: actions/cache@v3
      with:
        path: /home/runner/.cache/camoufox
        key: camoufox-${{ runner.os }}
    
    - name: Set up WARP
      uses: fscarmen/warp-on-actions@v1.3
      with:
        mode: 'client'
    
    - name: Run scraper
      run: python immoscrape.py
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: scraping-results
        path: |
          immobilienscout24.png
