name: run

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'
        cache-dependency-path: requirements.txt
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Cache Camoufox
      uses: actions/cache@v3
      with:
        path: /home/runner/.cache
        key:  runner-cache-${{ runner.os }}
    
    - name: Install WARP
      run: |
        curl https://pkg.cloudflareclient.com/pubkey.gpg | sudo apt-key add -
        echo "deb http://pkg.cloudflareclient.com/ focal main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
        sudo apt update
        sudo apt install cloudflare-warp
        warp-cli registration new
        warp-cli connect
        sleep 5
        WARP_STATUS=$(curl https://www.cloudflare.com/cdn-cgi/trace/ | grep "warp" | cut -d= -f2)
        if [ "$WARP_STATUS" != "on" ]; then
          echo "WARP is not enabled"
          exit 1
        fi
        echo "WARP is enabled and working"
    
    - name: Run scraper
      run: python immoscrape.py
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: scraping-results
        path: |
          immobilienscout24.png
